services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ocr_llm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  mineru:
    build:
      context: ./mineru
      args:
        MINERU_MODEL_SOURCE: huggingface
    restart: unless-stopped
    ports:
      - "8010:8010"

volumes:
  postgres_data: