"""add token counts

Revision ID: 07f020cb8990
Revises: af7cba3bae02
Create Date: 2026-08-14 13:33:39.881294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f020cb8990'
down_revision: Union[str, Sequence[str], None] = 'af7cba3bae02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tokens', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('markdown_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'markdown_tokens')
    op.drop_column('chat_messages', 'tokens')
    # ### end Alembic commands ###
