"""change schema

Revision ID: 7459d7d3cfda
Revises: c29060285a76
Create Date: 2026-08-04 17:25:59.518762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7459d7d3cfda'
down_revision: Union[str, Sequence[str], None] = 'c29060285a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('ocr_backend', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'done', 'failed')", name='ck_file_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_constraint("documents_session_id_fkey", "documents", type_="foreignkey",)
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'session_id')
    op.drop_index(op.f('ix_documents_message_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.drop_table('chat_sessions')
    op.drop_table('documents')
    op.add_column('chat_messages', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('chat_messages', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.add_column('chat_messages', sa.Column('model', sa.String(length=64), nullable=True))
    op.add_column('chat_messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_column('chat_messages', 'completion_tokens')
    op.drop_column('chat_messages', 'prompt_tokens')
    op.drop_column('chat_messages', 'model')
    op.drop_column('chat_messages', 'conversation_id')
    op.drop_column('chat_messages', 'user_id')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=127), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ocr_backend', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'done'::character varying, 'failed'::character varying]::text[])", name=op.f('ck_document_status')),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('documents_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('documents_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_index(op.f('ix_documents_message_id'), 'documents', ['message_id'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_sessions_pkey'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
