"""add file link

Revision ID: af7cba3bae02
Revises: 7459d7d3cfda
Create Date: 2026-08-07 23:41:32.468157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7cba3bae02'
down_revision: Union[str, Sequence[str], None] = '7459d7d3cfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_files_conversation_id'), 'files', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'files', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_conversation_id'), table_name='files')
    op.drop_column('files', 'conversation_id')
    # ### end Alembic commands ###
